const fs = require('fs');

const currentPlayersRaw = [
    ["Rodrigo Hernandez", "España", "Manchester City", "Atlético de Madrid", "Centrocampista defensivo", "Premier League"],
    ["Erling Haaland", "Noruega", "Manchester City", "Borussia Dortmund", "Delantero centro", "Premier League"],
    ["Kylian Mbappé", "Francia", "Real Madrid", "Paris Saint-Germain", "Delantero centro", "LaLiga"],
    ["Jude Bellingham", "Inglaterra", "Real Madrid", "Borussia Dortmund", "Centrocampista ofensivo", "LaLiga"],
    ["Vinícius Júnior", "Brasil", "Real Madrid", "Flamengo", "Extremo izquierdo", "LaLiga"],
    ["Kevin De Bruyne", "Bélgica", "Manchester City", "Wolfsburgo", "Centrocampista ofensivo", "Premier League"],
    ["Harry Kane", "Inglaterra", "Bayern Múnich", "Tottenham Hotspur", "Delantero centro", "Bundesliga"],
    ["Mohamed Salah", "Egipto", "Liverpool", "AS Roma", "Extremo derecho", "Premier League"],
    ["Lamine Yamal", "España", "Barcelona", "Barcelona Juvenil", "Extremo derecho", "LaLiga"],
    ["Phil Foden", "Inglaterra", "Manchester City", "City Juvenil", "Mediapunta", "Premier League"],
    ["Bukayo Saka", "Inglaterra", "Arsenal", "Arsenal Juvenil", "Extremo derecho", "Premier League"],
    ["Jamal Musiala", "Alemania", "Bayern Múnich", "Chelsea Juvenil", "Mediapunta", "Bundesliga"],
    ["Florian Wirtz", "Alemania", "Bayer Leverkusen", "Colonia Juvenil", "Mediapunta", "Bundesliga"],
    ["Pedri González", "España", "Barcelona", "Las Palmas", "Centrocampista", "LaLiga"],
    ["Pablo Gavi", "España", "Barcelona", "Betis Juvenil", "Centrocampista", "LaLiga"],
    ["Federico Valverde", "Uruguay", "Real Madrid", "Peñarol", "Centrocampista", "LaLiga"],
    ["Aurélien Tchouaméni", "Francia", "Real Madrid", "AS Mónaco", "Centrocampista defensivo", "LaLiga"],
    ["Eduardo Camavinga", "Francia", "Real Madrid", "Rennes", "Centrocampista", "LaLiga"],
    ["Rúben Dias", "Portugal", "Manchester City", "Benfica", "Defensa central", "Premier League"],
    ["William Saliba", "Francia", "Arsenal", "Saint-Étienne", "Defensa central", "Premier League"],
    ["Virgil van Dijk", "Países Bajos", "Liverpool", "Southampton", "Defensa central", "Premier League"],
    ["Trent Alexander-Arnold", "Inglaterra", "Liverpool", "Liverpool Juvenil", "Lateral derecho", "Premier League"],
    ["Josko Gvardiol", "Croacia", "Manchester City", "RB Leipzig", "Defensa central", "Premier League"],
    ["Nicolò Barella", "Italia", "Inter de Milán", "Cagliari", "Centrocampista", "Serie A"],
    ["Alessandro Bastoni", "Italia", "Inter de Milán", "Atalanta", "Defensa central", "Serie A"],
    ["Rafael Leão", "Portugal", "AC Milan", "Lille", "Extremo izquierdo", "Serie A"],
    ["Victor Osimhen", "Nigeria", "Napoli", "Lille", "Delantero centro", "Serie A"],
    ["Khvicha Kvaratskhelia", "Georgia", "Napoli", "Dinamo Batumi", "Extremo izquierdo", "Serie A"],
    ["Lautaro Martínez", "Argentina", "Inter de Milán", "Racing Club", "Delantero centro", "Serie A"],
    ["Julián Álvarez", "Argentina", "Manchester City", "River Plate", "Delantero centro", "Premier League"],
    ["Antoine Griezmann", "Francia", "Atlético de Madrid", "Barcelona", "Mediapunta", "LaLiga"],
    ["Ousmane Dembélé", "Francia", "Paris Saint-Germain", "Barcelona", "Extremo derecho", "Ligue 1"],
    ["Achraf Hakimi", "Marruecos", "Paris Saint-Germain", "Inter de Milán", "Lateral derecho", "Ligue 1"],
    ["Gianluigi Donnarumma", "Italia", "Paris Saint-Germain", "AC Milan", "Portero", "Ligue 1"],
    ["Alisson Becker", "Brasil", "Liverpool", "AS Roma", "Portero", "Premier League"],
    ["Ederson Moraes", "Brasil", "Manchester City", "Benfica", "Portero", "Premier League"],
    ["Thibaut Courtois", "Bélgica", "Real Madrid", "Chelsea", "Portero", "LaLiga"],
    ["Ronald Araújo", "Uruguay", "Barcelona", "Boston River", "Defensa central", "LaLiga"],
    ["Jules Koundé", "Francia", "Barcelona", "Sevilla", "Lateral derecho", "LaLiga"],
    ["Alphonso Davies", "Canadá", "Bayern Múnich", "Vancouver Whitecaps", "Lateral izquierdo", "Bundesliga"],
    ["Joshua Kimmich", "Alemania", "Bayern Múnich", "RB Leipzig", "Centrocampista defensivo", "Bundesliga"],
    ["Leroy Sané", "Alemania", "Bayern Múnich", "Manchester City", "Extremo derecho", "Bundesliga"],
    ["Serge Gnabry", "Alemania", "Bayern Múnich", "Werder Bremen", "Extremo derecho", "Bundesliga"],
    ["Jack Grealish", "Inglaterra", "Manchester City", "Aston Villa", "Extremo izquierdo", "Premier League"],
    ["Bernardo Silva", "Portugal", "Manchester City", "AS Mónaco", "Centrocampista ofensivo", "Premier League"],
    ["Bruno Fernandes", "Portugal", "Manchester United", "Sporting CP", "Centrocampista ofensivo", "Premier League"],
    ["Marcus Rashford", "Inglaterra", "Manchester United", "United Juvenil", "Extremo izquierdo", "Premier League"],
    ["Ollie Watkins", "Inglaterra", "Aston Villa", "Brentford", "Delantero centro", "Premier League"],
    ["Alexander Isak", "Suecia", "Newcastle United", "Real Sociedad", "Delantero centro", "Premier League"],
    ["Bruno Guimarães", "Brasil", "Newcastle United", "Lyon", "Centrocampista defensivo", "Premier League"],
    ["Declan Rice", "Inglaterra", "Arsenal", "West Ham", "Centrocampista defensivo", "Premier League"],
    ["Martin Ødegaard", "Noruega", "Arsenal", "Real Madrid", "Centrocampista ofensivo", "Premier League"],
    ["Gabriel Martinelli", "Brasil", "Arsenal", "Ituano", "Extremo izquierdo", "Premier League"],
    ["Kai Havertz", "Alemania", "Arsenal", "Chelsea", "Mediapunta", "Premier League"],
    ["Heung-min Son", "Corea del Sur", "Tottenham Hotspur", "Bayer Leverkusen", "Extremo izquierdo", "Premier League"],
    ["James Maddison", "Inglaterra", "Tottenham Hotspur", "Leicester City", "Centrocampista ofensivo", "Premier League"],
    ["Cristian Romero", "Argentina", "Tottenham Hotspur", "Atalanta", "Defensa central", "Premier League"],
    ["Dominik Szoboszlai", "Hungría", "Liverpool", "RB Leipzig", "Centrocampista ofensivo", "Premier League"],
    ["Alexis Mac Allister", "Argentina", "Liverpool", "Brighton", "Centrocampista", "Premier League"],
    ["Luis Díaz", "Colombia", "Liverpool", "FC Porto", "Extremo izquierdo", "Premier League"],
    ["Darwin Núñez", "Uruguay", "Liverpool", "Benfica", "Delantero centro", "Premier League"],
    ["Diogo Jota", "Portugal", "Liverpool", "Wolverhampton", "Delantero centro", "Premier League"],
    ["Cody Gakpo", "Países Bajos", "Liverpool", "PSV Eindhoven", "Extremo izquierdo", "Premier League"],
    ["Andrew Robertson", "Escocia", "Liverpool", "Hull City", "Lateral izquierdo", "Premier League"],
    ["Mike Maignan", "Francia", "AC Milan", "Lille", "Portero", "Serie A"],
    ["Theo Hernández", "Francia", "AC Milan", "Real Madrid", "Lateral izquierdo", "Serie A"],
    ["Christian Pulisic", "Estados Unidos", "AC Milan", "Chelsea", "Extremo derecho", "Serie A"],
    ["Ruben Loftus-Cheek", "Inglaterra", "AC Milan", "Chelsea", "Centrocampista", "Serie A"],
    ["Fikayo Tomori", "Inglaterra", "AC Milan", "Chelsea", "Defensa central", "Serie A"],
    ["Álvaro Morata", "España", "AC Milan", "Atlético de Madrid", "Delantero centro", "Serie A"],
    ["Dušan Vlahović", "Serbia", "Juventus", "Fiorentina", "Delantero centro", "Serie A"],
    ["Federico Chiesa", "Italia", "Liverpool", "Juventus", "Extremo", "Premier League"],
    ["Gleison Bremer", "Brasil", "Juventus", "Torino", "Defensa central", "Serie A"],
    ["Adrien Rabiot", "Francia", "Juventus", "Paris Saint-Germain", "Centrocampista", "Serie A"],
    ["Yann Sommer", "Suiza", "Inter de Milán", "Bayern Múnich", "Portero", "Serie A"],
    ["Hakan Çalhanoğlu", "Turquía", "Inter de Milán", "AC Milan", "Centrocampista", "Serie A"],
    ["Henrikh Mkhitaryan", "Armenia", "Inter de Milán", "AS Roma", "Centrocampista", "Serie A"],
    ["Marcus Thuram", "Francia", "Inter de Milán", "B. Mönchengladbach", "Delantero centro", "Serie A"],
    ["Benjamin Pavard", "Francia", "Inter de Milán", "Bayern Múnich", "Defensa central", "Serie A"],
    ["Federico Dimarco", "Italia", "Inter de Milán", "Verona", "Lateral izquierdo", "Serie A"],
    ["Giovanni Di Lorenzo", "Italia", "Napoli", "Empoli", "Lateral derecho", "Serie A"],
    ["Stanislav Lobotka", "Eslovaquia", "Napoli", "Celta de Vigo", "Centrocampista defensivo", "Serie A"],
    ["Frank Anguissa", "Camerún", "Napoli", "Fulham", "Centrocampista", "Serie A"],
    ["Alex Meret", "Italia", "Napoli", "Udinese", "Portero", "Serie A"],
    ["Amir Rrahmani", "Kosovo", "Napoli", "Verona", "Defensa central", "Serie A"],
    ["Granit Xhaka", "Suiza", "Bayer Leverkusen", "Arsenal", "Centrocampista", "Bundesliga"],
    ["Alejandro Grimaldo", "España", "Bayer Leverkusen", "Benfica", "Lateral izquierdo", "Bundesliga"],
    ["Jeremie Frimpong", "Países Bajos", "Bayer Leverkusen", "Celtic", "Lateral derecho", "Bundesliga"],
    ["Exequiel Palacios", "Argentina", "Bayer Leverkusen", "River Plate", "Centrocampista", "Bundesliga"],
    ["Jonathan Tah", "Alemania", "Bayer Leverkusen", "Hamburgo", "Defensa central", "Bundesliga"],
    ["Edmond Tapsoba", "Burkina Faso", "Bayer Leverkusen", "V. Guimarães", "Defensa central", "Bundesliga"],
    ["Piero Hincapié", "Ecuador", "Bayer Leverkusen", "Talleres", "Defensa central", "Bundesliga"],
    ["Victor Boniface", "Nigeria", "Bayer Leverkusen", "Union SG", "Delantero centro", "Bundesliga"],
    ["Patrik Schick", "República Checa", "Bayer Leverkusen", "AS Roma", "Delantero centro", "Bundesliga"],
    ["Jonas Hofmann", "Alemania", "Bayer Leverkusen", "Mönchengladbach", "Centrocampista ofensivo", "Bundesliga"],
    ["Gregor Kobel", "Suiza", "Borussia Dortmund", "Stuttgart", "Portero", "Bundesliga"],
    ["Nico Schlotterbeck", "Alemania", "Borussia Dortmund", "Friburgo", "Defensa central", "Bundesliga"],
    ["Niklas Süle", "Alemania", "Borussia Dortmund", "Bayern Múnich", "Defensa central", "Bundesliga"],
    ["Julian Ryerson", "Noruega", "Borussia Dortmund", "Union Berlin", "Lateral derecho", "Bundesliga"],
    ["Emre Can", "Alemania", "Borussia Dortmund", "Juventus", "Centrocampista", "Bundesliga"],
    ["Marcel Sabitzer", "Austria", "Borussia Dortmund", "Bayern Múnich", "Centrocampista", "Bundesliga"],
    ["Julian Brandt", "Alemania", "Borussia Dortmund", "Bayer Leverkusen", "Mediapunta", "Bundesliga"],
    ["Donyell Malen", "Países Bajos", "Borussia Dortmund", "PSV Eindhoven", "Extremo derecho", "Bundesliga"],
    ["Karim Adeyemi", "Alemania", "Borussia Dortmund", "RB Salzburg", "Extremo izquierdo", "Bundesliga"],
    ["Niclas Füllkrug", "Alemania", "West Ham", "Borussia Dortmund", "Delantero centro", "Premier League"],
    ["Marquinhos Aoás", "Brasil", "Paris Saint-Germain", "AS Roma", "Defensa central", "Ligue 1"],
    ["Vitinha Machado", "Portugal", "Paris Saint-Germain", "FC Porto", "Centrocampista", "Ligue 1"],
    ["Warren Zaïre-Emery", "Francia", "Paris Saint-Germain", "PSG Juvenil", "Centrocampista", "Ligue 1"],
    ["Randal Kolo Muani", "Francia", "Paris Saint-Germain", "Eintracht Frankfurt", "Delantero centro", "Ligue 1"],
    ["Lucas Hernández", "Francia", "Paris Saint-Germain", "Bayern Múnich", "Defensa central", "Ligue 1"],
    ["Milan Skriniar", "Eslovaquia", "Paris Saint-Germain", "Inter de Milán", "Defensa central", "Ligue 1"],
    ["Nuno Mendes", "Portugal", "Paris Saint-Germain", "Sporting CP", "Lateral izquierdo", "Ligue 1"],
    ["Gonçalo Ramos", "Portugal", "Paris Saint-Germain", "Benfica", "Delantero centro", "Ligue 1"],
    ["Fabián Ruiz", "España", "Paris Saint-Germain", "Napoli", "Centrocampista", "Ligue 1"],
    ["Matthijs de Ligt", "Países Bajos", "Manchester United", "Bayern Múnich", "Defensa central", "Premier League"],
    ["Leon Goretzka", "Alemania", "Bayern Múnich", "Schalke 04", "Centrocampista", "Bundesliga"],
    ["Thomas Müller", "Alemania", "Bayern Múnich", "Bayern Múnich Juvenil", "Mediapunta", "Bundesliga"],
    ["Dayot Upamecano", "Francia", "Bayern Múnich", "RB Leipzig", "Defensa central", "Bundesliga"],
    ["Kingsley Coman", "Francia", "Bayern Múnich", "Juventus", "Extremo", "Bundesliga"],
    ["Min-jae Kim", "Corea del Sur", "Bayern Múnich", "Napoli", "Defensa central", "Bundesliga"],
    ["Xavi Simons", "Países Bajos", "RB Leipzig", "PSV Eindhoven", "Mediapunta", "Bundesliga"],
    ["Dani Olmo", "España", "Barcelona", "RB Leipzig", "Mediapunta", "LaLiga"],
    ["Loïs Openda", "Bélgica", "RB Leipzig", "Lens", "Delantero centro", "Bundesliga"],
    ["Benjamin Šeško", "Eslovenia", "RB Leipzig", "RB Salzburg", "Delantero centro", "Bundesliga"],
    ["Antony Santos", "Brasil", "Manchester United", "Ajax", "Extremo derecho", "Premier League"],
    ["Lisandro Martínez", "Argentina", "Manchester United", "Ajax", "Defensa central", "Premier League"],
    ["Casemiro", "Brasil", "Manchester United", "Real Madrid", "Centrocampista defensivo", "Premier League"],
    ["Luke Shaw", "Inglaterra", "Manchester United", "Southampton", "Lateral izquierdo", "Premier League"],
    ["Alejandro Garnacho", "Argentina", "Manchester United", "Atlético Juvenil", "Extremo izquierdo", "Premier League"],
    ["Rasmus Højlund", "Dinamarca", "Manchester United", "Atalanta", "Delantero centro", "Premier League"],
    ["Cole Palmer", "Inglaterra", "Chelsea", "Manchester City", "Mediapunta", "Premier League"],
    ["Enzo Fernández", "Argentina", "Chelsea", "Benfica", "Centrocampista", "Premier League"],
    ["Moisés Caicedo", "Ecuador", "Chelsea", "Brighton", "Centrocampista defensivo", "Premier League"],
    ["Reece James", "Inglaterra", "Chelsea", "Wigan Athletic", "Lateral derecho", "Premier League"],
    ["Mykhailo Mudryk", "Ucrania", "Chelsea", "Shakhtar Donetsk", "Extremo izquierdo", "Premier League"],
    ["Raheem Sterling", "Inglaterra", "Arsenal", "Chelsea", "Extremo izquierdo", "Premier League"],
    ["Nicolas Jackson", "Senegal", "Chelsea", "Villarreal", "Delantero centro", "Premier League"],
    ["Christopher Nkunku", "Francia", "Chelsea", "RB Leipzig", "Mediapunta", "Premier League"],
    ["Sandro Tonali", "Italia", "Newcastle United", "AC Milan", "Centrocampista", "Premier League"],
    ["Joelinton Cassio", "Brasil", "Newcastle United", "Hoffenheim", "Centrocampista", "Premier League"],
    ["Kieran Trippier", "Inglaterra", "Newcastle United", "Atlético de Madrid", "Lateral derecho", "Premier League"],
    ["Anthony Gordon", "Inglaterra", "Newcastle United", "Everton", "Extremo izquierdo", "Premier League"],
    ["Nick Pope", "Inglaterra", "Newcastle United", "Burnley", "Portero", "Premier League"],
    ["Sven Botman", "Países Bajos", "Newcastle United", "Lille", "Defensa central", "Premier League"],
    ["Eberechi Eze", "Inglaterra", "Crystal Palace", "QPR", "Mediapunta", "Premier League"],
    ["Michael Olise", "Francia", "Bayern Múnich", "Crystal Palace", "Extremo derecho", "Bundesliga"],
    ["Jarrod Bowen", "Inglaterra", "West Ham", "Hull City", "Extremo derecho", "Premier League"],
    ["Lucas Paquetá", "Brasil", "West Ham", "Lyon", "Mediapunta", "Premier League"],
    ["Edson Álvarez", "México", "West Ham", "Ajax", "Centrocampista defensivo", "Premier League"],
    ["Kudus Mohammed", "Ghana", "West Ham", "Ajax", "Extremo derecho", "Premier League"],
    ["Jo\u00e3o Palhinha", "Portugal", "Bayern Múnich", "Fulham", "Centrocampista defensivo", "Bundesliga"],
    ["Douglas Luiz", "Brasil", "Juventus", "Aston Villa", "Centrocampista", "Serie A"],
    ["John McGinn", "Escocia", "Aston Villa", "Hibernian", "Centrocampista", "Premier League"],
    ["Leon Bailey", "Jamaica", "Aston Villa", "Bayer Leverkusen", "Extremo derecho", "Premier League"],
    ["Pau Torres", "España", "Aston Villa", "Villarreal", "Defensa central", "Premier League"],
    ["Emiliano Martínez", "Argentina", "Aston Villa", "Arsenal", "Portero", "Premier League"],
    ["Kaoru Mitoma", "Japón", "Brighton", "Union SG", "Extremo izquierdo", "Premier League"],
    ["Pervis Estupiñán", "Ecuador", "Brighton", "Villarreal", "Lateral izquierdo", "Premier League"],
    ["Evan Ferguson", "Irlanda", "Brighton", "Bohemians", "Delantero centro", "Premier League"],
    ["João Pedro", "Brasil", "Brighton", "Watford", "Delantero centro", "Premier League"],
    ["Ivan Toney", "Inglaterra", "Al-Ahli", "Brentford", "Delantero centro", "Saudi Pro League"],
    ["Bryan Mbeumo", "Camerún", "Brentford", "Troyes", "Extremo derecho", "Premier League"],
    ["Dominic Solanke", "Inglaterra", "Tottenham Hotspur", "Bournemouth", "Delantero centro", "Premier League"],
    ["Andreas Christensen", "Dinamarca", "Barcelona", "Chelsea", "Defensa central", "LaLiga"],
    ["Frenkie de Jong", "Países Bajos", "Barcelona", "Ajax", "Centrocampista", "LaLiga"],
    ["Raphael Dias Belloli", "Brasil", "Barcelona", "Leeds United", "Extremo derecho", "LaLiga"],
    ["Robert Lewandowski", "Polonia", "Barcelona", "Bayern Múnich", "Delantero centro", "LaLiga"],
    ["Ferran Torres", "España", "Barcelona", "Manchester City", "Extremo", "LaLiga"],
    ["Marc-André ter Stegen", "Alemania", "Barcelona", "Mönchengladbach", "Portero", "LaLiga"],
    ["João Cancelo", "Portugal", "Al-Hilal", "Manchester City", "Lateral derecho", "Saudi Pro League"],
    ["João Félix", "Portugal", "Chelsea", "Atlético de Madrid", "Mediapunta", "Premier League"],
    ["Nahuel Molina", "Argentina", "Atlético de Madrid", "Udinese", "Lateral derecho", "LaLiga"],
    ["José Giménez", "Uruguay", "Atlético de Madrid", "Danubio", "Defensa central", "LaLiga"],
    ["Koke Resurrección", "España", "Atlético de Madrid", "Atlético Juvenil", "Centrocampista", "LaLiga"],
    ["Marcos Llorente", "España", "Atlético de Madrid", "Real Madrid", "Centrocampista", "LaLiga"],
    ["Rodrigo De Paul", "Argentina", "Atlético de Madrid", "Udinese", "Centrocampista", "LaLiga"],
    ["Jan Oblak", "Eslovenia", "Atlético de Madrid", "Benfica", "Portero", "LaLiga"],
    ["Mikel Oyarzabal", "España", "Real Sociedad", "Real Sociedad Juvenil", "Extremo", "LaLiga"],
    ["Mikel Merino", "España", "Arsenal", "Real Sociedad", "Centrocampista", "Premier League"],
    ["Takefusa Kubo", "Japón", "Real Sociedad", "Real Madrid", "Extremo derecho", "LaLiga"],
    ["Unai Simón", "España", "Athletic Club", "Athletic Juvenil", "Portero", "LaLiga"],
    ["Nico Williams", "España", "Athletic Club", "Athletic Juvenil", "Extremo izquierdo", "LaLiga"],
    ["Iñaki Williams", "Ghana", "Athletic Club", "Athletic Juvenil", "Delantero", "LaLiga"],
    ["Oihan Sancet", "España", "Athletic Club", "Athletic Juvenil", "Mediapunta", "LaLiga"],
    ["Gerard Moreno", "España", "Villarreal", "Espanyol", "Delantero", "LaLiga"],
    ["Dani Parejo", "España", "Villarreal", "Valencia", "Centrocampista", "LaLiga"],
    ["Álex Baena", "España", "Villarreal", "Villarreal Juvenil", "Centrocampista ofensivo", "LaLiga"],
    ["Francisco Alarcón Isco", "España", "Real Betis", "Sevilla", "Mediapunta", "LaLiga"],
    ["Nabil Fekir", "Francia", "Real Betis", "Lyon", "Mediapunta", "LaLiga"],
    ["Guido Rodríguez", "Argentina", "West Ham", "Real Betis", "Centrocampista defensivo", "Premier League"],
    ["Youssef En-Nesyri", "Marruecos", "Fenerbahçe", "Sevilla", "Delantero centro", "Süper Lig"],
    ["Lucas Ocampos", "Argentina", "Sevilla", "Marseille", "Extremo", "LaLiga"],
    ["Brahim Díaz", "Marruecos", "Real Madrid", "AC Milan", "Mediapunta", "LaLiga"],
    ["Rodrygo Goes", "Brasil", "Real Madrid", "Santos", "Extremo derecho", "LaLiga"],
    ["Éder Militão", "Brasil", "Real Madrid", "FC Porto", "Defensa central", "LaLiga"],
    ["David Alaba", "Austria", "Real Madrid", "Bayern Múnich", "Defensa central", "LaLiga"],
    ["Antonio Rüdiger", "Alemania", "Real Madrid", "Chelsea", "Defensa central", "LaLiga"],
    ["Dani Carvajal", "España", "Real Madrid", "Bayer Leverkusen", "Lateral derecho", "LaLiga"],
    ["Miguel Almirón", "Paraguay", "Newcastle United", "Atlanta United", "Extremo derecho", "Premier League"],
    ["Nathan Aké", "Países Bajos", "Manchester City", "Bournemouth", "Defensa central", "Premier League"],
    ["Kyle Walker", "Inglaterra", "Manchester City", "Tottenham", "Lateral derecho", "Premier League"],
    ["John Stones", "Inglaterra", "Manchester City", "Everton", "Defensa central", "Premier League"],
    ["Manuel Akanji", "Suiza", "Manchester City", "Borussia Dortmund", "Defensa central", "Premier League"],
    ["Rico Lewis", "Inglaterra", "Manchester City", "City Juvenil", "Lateral derecho", "Premier League"],
    ["Stefan Ortega", "Alemania", "Manchester City", "Arminia Bielefeld", "Portero", "Premier League"],
    ["Kepa Arrizabalaga", "España", "Bournemouth", "Chelsea", "Portero", "Premier League"],
    ["Marc Cucurella", "España", "Chelsea", "Brighton", "Lateral izquierdo", "Premier League"],
    ["Levi Colwill", "Inglaterra", "Chelsea", "Chelsea Juvenil", "Defensa central", "Premier League"],
    ["Axel Disasi", "Francia", "Chelsea", "AS Monaco", "Defensa central", "Premier League"],
    ["Benoît Badiashile", "Francia", "Chelsea", "AS Monaco", "Defensa central", "Premier League"],
    ["Ben Chilwell", "Inglaterra", "Chelsea", "Leicester City", "Lateral izquierdo", "Premier League"],
    ["Conor Gallagher", "Inglaterra", "Atlético de Madrid", "Chelsea", "Centrocampista", "LaLiga"],
    ["Roméo Lavia", "Bélgica", "Chelsea", "Southampton", "Centrocampista defensivo", "Premier League"],
    ["Destiny Udogie", "Italia", "Tottenham Hotspur", "Udinese", "Lateral izquierdo", "Premier League"],
    ["Guglielmo Vicario", "Italia", "Tottenham Hotspur", "Empoli", "Portero", "Premier League"],
    ["Pedro Porro", "España", "Tottenham Hotspur", "Sporting CP", "Lateral derecho", "Premier League"],
    ["Pape Matar Sarr", "Senegal", "Tottenham Hotspur", "Metz", "Centrocampista", "Premier League"],
    ["Yves Bissouma", "Mali", "Tottenham Hotspur", "Brighton", "Centrocampista defensivo", "Premier League"],
    ["Dejan Kulusevski", "Suecia", "Tottenham Hotspur", "Juventus", "Extremo derecho", "Premier League"],
    ["Brennan Johnson", "Gales", "Tottenham Hotspur", "Nottingham Forest", "Extremo derecho", "Premier League"],
    ["Timo Werner", "Alemania", "Tottenham Hotspur", "RB Leipzig", "Extremo izquierdo", "Premier League"],
    ["Ibrahima Konaté", "Francia", "Liverpool", "RB Leipzig", "Defensa central", "Premier League"],
    ["Joe Gomez", "Inglaterra", "Liverpool", "Charlton", "Defensa central", "Premier League"],
    ["Kostas Tsimikas", "Grecia", "Liverpool", "Olympiacos", "Lateral izquierdo", "Premier League"],
    ["Ryan Gravenberch", "Países Bajos", "Liverpool", "Bayern Múnich", "Centrocampista", "Premier League"],
    ["Wataru Endo", "Japón", "Liverpool", "Stuttgart", "Centrocampista defensivo", "Premier League"],
    ["Harvey Elliott", "Inglaterra", "Liverpool", "Fulham", "Centrocampista ofensivo", "Premier League"],
    ["Curtis Jones", "Inglaterra", "Liverpool", "Liverpool Juvenil", "Centrocampista", "Premier League"],
    ["Martín Zubimendi", "España", "Real Sociedad", "Real Sociedad Juvenil", "Centrocampista defensivo", "LaLiga"],
    ["Aymeric Laporte", "España", "Al-Nassr", "Manchester City", "Defensa central", "Saudi Pro League"],
    ["Marcelo Brozović", "Croacia", "Al-Nassr", "Inter de Milán", "Centrocampista defensivo", "Saudi Pro League"],
    ["Kpler Laveran Pepe", "Portugal", "FC Porto", "Real Madrid", "Defensa central", "Primeira Liga"],
    ["Alejandro Balde", "España", "Barcelona", "Barcelona Juvenil", "Lateral izquierdo", "LaLiga"],
    ["César Azpilicueta", "España", "Atlético de Madrid", "Chelsea", "Defensa central", "LaLiga"],
    ["Memphis Depay", "Países Bajos", "Corinthians", "Atlético de Madrid", "Delantero centro", "Brasileirão"],
    ["Gabriel Jesús", "Brasil", "Arsenal", "Manchester City", "Delantero", "Premier League"],
    ["Ivan Perišić", "Croacia", "Hajduk Split", "Tottenham", "Extremo izquierdo", "HNL"],
    ["Ángel Di María", "Argentina", "Benfica", "Juventus", "Extremo derecho", "Primeira Liga"],
    ["Sadio Mané", "Senegal", "Al-Nassr", "Bayern Múnich", "Extremo izquierdo", "Saudi Pro League"],
    ["Roberto Firmino", "Brasil", "Al-Ahli", "Liverpool", "Delantero", "Saudi Pro League"],
    ["Neymar da Silva", "Brasil", "Al-Hilal", "Paris Saint-Germain", "Extremo izquierdo", "Saudi Pro League"],
    ["Cristiano Ronaldo", "Portugal", "Al-Nassr", "Manchester United", "Delantero", "Saudi Pro League"],
    ["Lionel Messi", "Argentina", "Inter Miami", "Paris Saint-Germain", "Mediapunta", "MLS"],
    ["Luis Suárez", "Uruguay", "Inter Miami", "Gremio", "Delantero", "MLS"],
    ["Sergio Busquets", "España", "Inter Miami", "Barcelona", "Centrocampista defensivo", "MLS"],
    ["Jordi Alba", "España", "Inter Miami", "Barcelona", "Lateral izquierdo", "MLS"],
    ["Karim Benzema", "Francia", "Al-Ittihad", "Real Madrid", "Delantero", "Saudi Pro League"],
    ["N'Golo Kanté", "Francia", "Al-Ittihad", "Chelsea", "Centrocampista defensivo", "Saudi Pro League"],
    ["Riyad Mahrez", "Argelia", "Al-Ahli", "Manchester City", "Extremo derecho", "Saudi Pro League"],
    ["Édouard Mendy", "Senegal", "Al-Ahli", "Chelsea", "Portero", "Saudi Pro League"],
    ["Kalidou Koulibaly", "Senegal", "Al-Hilal", "Chelsea", "Defensa central", "Saudi Pro League"],
    ["Rúben Neves", "Portugal", "Al-Hilal", "Wolverhampton", "Centrocampista defensivo", "Saudi Pro League"],
    ["Sergej Milinković-Savić", "Serbia", "Al-Hilal", "Lazio", "Centrocampista", "Saudi Pro League"],
    ["Leandro Trossard", "Bélgica", "Arsenal", "Brighton", "Extremo izquierdo", "Premier League"],
    ["Christian Eriksen", "Dinamarca", "Manchester United", "Brentford", "Centrocampista", "Premier League"],
    ["Manuel Neuer", "Alemania", "Bayern Múnich", "Schalke 04", "Portero", "Bundesliga"],
    ["Marc Guéhi", "Inglaterra", "Crystal Palace", "Chelsea", "Defensa central", "Premier League"]
];

const legendPlayersRaw = [
    ["Gerd Müller", "Alemania", "Bayern Múnich", "Delantero", "1970s"],
    ["Lev Yashin", "Rusia", "Dinamo Moscú", "Portero", "1950s-1960s"],
    ["Paolo Rossi", "Italia", "Juventus", "Delantero", "1980s"],
    ["George Best", "Irlanda del Norte", "Manchester United", "Extremo", "1960s-1970s"],
    ["Bobby Charlton", "Inglaterra", "Manchester United", "Centrocampista ofensivo", "1960s-1970s"],
    ["Franz Beckenbauer", "Alemania", "Bayern Múnich", "Líbero", "1970s"],
    ["Johan Cruyff", "Países Bajos", "Ajax", "Delantero", "1970s"],
    ["Diego Maradona", "Argentina", "Napoli", "Centrocampista ofensivo", "1980s"],
    ["Edson Arantes Pelé", "Brasil", "Santos", "Delantero", "1960s-1970s"],
    ["Zinedine Zidane", "Francia", "Real Madrid", "Centrocampista ofensivo", "1990s-2000s"],
    ["Ronaldo Nazário", "Brasil", "Real Madrid", "Delantero", "1990s-2000s"],
    ["Ronaldinho Gaúcho", "Brasil", "Barcelona", "Mediapunta", "2000s"],
    ["Paolo Maldini", "Italia", "AC Milan", "Defensa", "1990s-2000s"],
    ["Alfredo Di Stéfano", "Argentina", "Real Madrid", "Delantero", "1950s"],
    ["Xavi Hernández", "España", "Barcelona", "Centrocampista", "2000s-2010s"],
    ["Andrés Iniesta", "España", "Barcelona", "Centrocampista", "2000s-2010s"],
    ["Thierry Henry", "Francia", "Arsenal", "Delantero", "2000s"],
    ["Dennis Bergkamp", "Países Bajos", "Arsenal", "Mediapunta", "1990s-2000s"],
    ["Roberto Baggio", "Italia", "Juventus", "Delantero", "1990s"],
    ["Ruud Gullit", "Países Bajos", "AC Milan", "Mediapunta", "1980s-1990s"],
    ["Marco van Basten", "Países Bajos", "AC Milan", "Delantero", "1980s-1990s"],
    ["Frank Rijkaard", "Países Bajos", "AC Milan", "Centrocampista defensivo", "1980s-1990s"],
    ["Lothar Matthäus", "Alemania", "Bayern Múnich", "Líbero", "1980s-1990s"],
    ["Franco Baresi", "Italia", "AC Milan", "Defensa central", "1980s-1990s"],
    ["Luís Figo", "Portugal", "Real Madrid", "Extremo", "1990s-2000s"],
    ["Pavel Nedvěd", "República Checa", "Juventus", "Centrocampista", "1990s-2000s"],
    ["Vítor Borba Rivaldo", "Brasil", "Barcelona", "Mediapunta", "1990s-2000s"],
    ["Ricardo Kaká", "Brasil", "AC Milan", "Centrocampista ofensivo", "2000s"],
    ["Andriy Shevchenko", "Ucrania", "AC Milan", "Delantero", "2000s"],
    ["Eusébio da Silva", "Portugal", "Benfica", "Delantero", "1960s"],
    ["Garrincha", "Brasil", "Botafogo", "Extremo derecho", "1960s"],
    ["Ferenc Puskás", "Hungría", "Real Madrid", "Delantero", "1950s"],
    ["Michel Platini", "Francia", "Juventus", "Mediapunta", "1980s"],
    ["Arthur Antunes Zico", "Brasil", "Flamengo", "Mediapunta", "1980s"],
    ["Roberto Carlos", "Brasil", "Real Madrid", "Lateral izquierdo", "1990s-2000s"],
    ["Marcos Cafu", "Brasil", "AC Milan", "Lateral derecho", "1990s-2000s"],
    ["Javier Zanetti", "Argentina", "Inter de Milán", "Lateral derecho", "1990s-2010s"],
    ["Ryan Giggs", "Gales", "Manchester United", "Extremo izquierdo", "1990s-2010s"],
    ["Paul Scholes", "Inglaterra", "Manchester United", "Centrocampista", "1990s-2010s"],
    ["Roy Keane", "Irlanda", "Manchester United", "Centrocampista defensivo", "1990s-2000s"],
    ["Patrick Vieira", "Francia", "Arsenal", "Centrocampista defensivo", "1990s-2000s"],
    ["Oliver Kahn", "Alemania", "Bayern Múnich", "Portero", "1990s-2000s"],
    ["Gianluigi Buffon", "Italia", "Juventus", "Portero", "1990s-2010s"],
    ["Iker Casillas", "España", "Real Madrid", "Portero", "2000s-2010s"],
    ["Carles Puyol", "España", "Barcelona", "Defensa central", "2000s-2010s"],
    ["Sergio Ramos", "España", "Real Madrid", "Defensa central", "2000s-2010s"],
    ["Gerard Piqué", "España", "Barcelona", "Defensa central", "2000s-2010s"],
    ["David Villa", "España", "Barcelona", "Delantero", "2000s-2010s"],
    ["Fernando Torres", "España", "Liverpool", "Delantero", "2000s-2010s"],
    ["Raúl González", "España", "Real Madrid", "Delantero", "1990s-2000s"],
    ["José María Guti", "España", "Real Madrid", "Centrocampista", "1990s-2000s"],
    ["Fernando Hierro", "España", "Real Madrid", "Defensa central", "1990s-2000s"],
    ["Didier Drogba", "Costa de Marfil", "Chelsea", "Delantero", "2000s-2010s"],
    ["Frank Lampard", "Inglaterra", "Chelsea", "Centrocampista", "2000s-2010s"],
    ["John Terry", "Inglaterra", "Chelsea", "Defensa central", "2000s-2010s"],
    ["Wayne Rooney", "Inglaterra", "Manchester United", "Delantero", "2000s-2010s"],
    ["Rio Ferdinand", "Inglaterra", "Manchester United", "Defensa central", "2000s-2010s"],
    ["Nemanja Vidić", "Serbia", "Manchester United", "Defensa central", "2000s-2010s"],
    ["Petr Čech", "República Checa", "Chelsea", "Portero", "2000s-2010s"],
    ["Ashley Cole", "Inglaterra", "Chelsea", "Lateral izquierdo", "2000s-2010s"],
    ["Eric Cantona", "Francia", "Manchester United", "Mediapunta", "1990s"],
    ["Alan Shearer", "Inglaterra", "Newcastle United", "Delantero", "1990s-2000s"],
    ["Gabriel Batistuta", "Argentina", "Fiorentina", "Delantero", "1990s"],
    ["Juan Román Riquelme", "Argentina", "Boca Juniors", "Centrocampista", "2000s"],
    ["Carlos Tevez", "Argentina", "Juventus", "Delantero", "2000s-2010s"],
    ["Hernán Crespo", "Argentina", "Inter de Milán", "Delantero", "1990s-2000s"],
    ["Clarence Seedorf", "Países Bajos", "AC Milan", "Centrocampista", "1990s-2000s"],
    ["Edgar Davids", "Países Bajos", "Juventus", "Centrocampista defensivo", "1990s-2000s"],
    ["Alessandro Del Piero", "Italia", "Juventus", "Mediapunta", "1990s-2000s"],
    ["Francesco Totti", "Italia", "AS Roma", "Mediapunta", "1990s-2010s"],
    ["Fabio Cannavaro", "Italia", "Juventus", "Defensa central", "1990s-2000s"],
    ["Alessandro Nesta", "Italia", "AC Milan", "Defensa central", "1990s-2000s"],
    ["Philipp Lahm", "Alemania", "Bayern Múnich", "Lateral derecho", "2000s-2010s"],
    ["Bastian Schweinsteiger", "Alemania", "Bayern Múnich", "Centrocampista", "2000s-2010s"],
    ["Miroslav Klose", "Alemania", "Lazio", "Delantero", "2000s-2010s"],
    ["Arjen Robben", "Países Bajos", "Bayern Múnich", "Extremo derecho", "2000s-2010s"],
    ["Franck Ribéry", "Francia", "Bayern Múnich", "Extremo izquierdo", "2000s-2010s"],
    ["Samuel Eto'o", "Camerún", "Barcelona", "Delantero", "2000s-2010s"],
    ["Yayá Touré", "Costa de Marfil", "Manchester City", "Centrocampista", "2000s-2010s"],
    ["Romário de Souza", "Brasil", "Barcelona", "Delantero", "1990s"],
    ["José Roberto Bebeto", "Brasil", "Deportivo La Coruña", "Delantero", "1990s"],
    ["Hristo Stoichkov", "Bulgaria", "Barcelona", "Delantero", "1990s"],
    ["Brian Laudrup", "Dinamarca", "Rangers", "Mediapunta", "1990s"],
    ["Michael Laudrup", "Dinamarca", "Real Madrid", "Mediapunta", "1980s-1990s"],
    ["Davor Šuker", "Croacia", "Real Madrid", "Delantero", "1990s"],
    ["Zvonimir Boban", "Croacia", "AC Milan", "Centrocampista", "1990s"],
    ["Gheorghe Hagi", "Rumania", "Galatasaray", "Mediapunta", "1990s"],
    ["Hugo Sánchez", "México", "Real Madrid", "Delantero", "1980s-1990s"],
    ["George Weah", "Liberia", "AC Milan", "Delantero", "1990s"],
    ["Lilian Thuram", "Francia", "Juventus", "Defensa", "1990s-2000s"],
    ["Marcel Desailly", "Francia", "AC Milan", "Defensa central", "1990s-2000s"],
    ["Laurent Blanc", "Francia", "Manchester United", "Defensa central", "1990s"],
    ["Didier Deschamps", "Francia", "Juventus", "Centrocampista defensivo", "1990s"],
    ["Claude Makélélé", "Francia", "Chelsea", "Centrocampista defensivo", "2000s"],
    ["Edwin van der Sar", "Países Bajos", "Manchester United", "Portero", "1990s-2000s"],
    ["Rui Costa", "Portugal", "AC Milan", "Mediapunta", "1990s-2000s"],
    ["Anderson Deco", "Portugal", "Barcelona", "Centrocampista", "2000s"],
    ["Ricardo Carvalho", "Portugal", "Chelsea", "Defensa central", "2000s"],
    ["Matthias Sammer", "Alemania", "Borussia Dortmund", "Líbero", "1990s"],
    ["Karl-Heinz Rummenigge", "Alemania", "Bayern Múnich", "Delantero centro", "1970s-1980s"],
    ["Sepp Maier", "Alemania", "Bayern Múnich", "Portero", "1970s"],
    ["Paul Breitner", "Alemania", "Bayern Múnich", "Lateral izquierdo", "1970s-1980s"],
    ["Andreas Brehme", "Alemania", "Inter de Milán", "Lateral izquierdo", "1980s-1990s"],
    ["Rudi Völler", "Alemania", "AS Roma", "Delantero", "1980s-1990s"],
    ["Jürgen Klinsmann", "Alemania", "Tottenham Hotspur", "Delantero centro", "1990s"],
    ["Oliver Bierhoff", "Alemania", "AC Milan", "Delantero centro", "1990s-2000s"],
    ["Andreas Möller", "Alemania", "Borussia Dortmund", "Centrocampista ofensivo", "1990s"],
    ["Stefan Effenberg", "Alemania", "Bayern Múnich", "Centrocampista", "1990s-2000s"],
    ["Michael Ballack", "Alemania", "Chelsea", "Centrocampista", "2000s"],
    ["Mehmet Scholl", "Alemania", "Bayern Múnich", "Mediapunta", "1990s-2000s"],
    ["Jens Lehmann", "Alemania", "Arsenal", "Portero", "2000s"],
    ["Gheorghe Popescu", "Rumania", "Barcelona", "Defensa central", "1990s"],
    ["Dan Petrescu", "Rumania", "Chelsea", "Lateral derecho", "1990s-2000s"],
    ["Ilie Dumitrescu", "Rumania", "Tottenham Hotspur", "Extremo", "1990s"],
    ["Krasimir Balakov", "Bulgaria", "Stuttgart", "Centrocampista", "1990s-2000s"],
    ["Yordan Letchkov", "Bulgaria", "Hamburgo", "Centrocampista", "1990s"],
    ["Dejan Savićević", "Montenegro", "AC Milan", "Mediapunta", "1990s"],
    ["Dragan Stojković", "Serbia", "Marseille", "Centrocampista ofensivo", "1990s"],
    ["Predrag Mijatović", "Montenegro", "Real Madrid", "Delantero", "1990s"],
    ["Siniša Mihajlović", "Serbia", "Lazio", "Defensa central", "1990s-2000s"],
    ["Slaven Bilić", "Croacia", "West Ham", "Defensa central", "1990s"],
    ["Dario Šimić", "Croacia", "AC Milan", "Defensa central", "1990s-2000s"],
    ["Zlatko Zahovič", "Eslovenia", "FC Porto", "Centrocampista ofensivo", "1990s-2000s"],
    ["Hakan Şükür", "Turquía", "Galatasaray", "Delantero centro", "1990s-2000s"],
    ["Rüştü Reçber", "Turquía", "Fenerbahçe", "Portero", "1990s-2000s"],
    ["Emre Belözoğlu", "Turquía", "Fenerbahçe", "Centrocampista", "2000s-2010s"],
    ["Tugay Kerimoğlu", "Turquía", "Blackburn Rovers", "Centrocampista defensivo", "2000s"],
    ["Jay-Jay Okocha", "Nigeria", "Bolton Wanderers", "Centrocampista ofensivo", "1990s-2000s"],
    ["Nwankwo Kanu", "Nigeria", "Arsenal", "Delantero", "1990s-2000s"],
    ["Finidi George", "Nigeria", "Ajax", "Extremo derecho", "1990s"],
    ["Taribo West", "Nigeria", "Inter de Milán", "Defensa central", "1990s"],
    ["Celestine Babayaro", "Nigeria", "Chelsea", "Lateral izquierdo", "1990s-2000s"],
    ["Rigobert Song", "Camerún", "Galatasaray", "Defensa central", "1990s-2000s"],
    ["Geremi Njitap", "Camerún", "Chelsea", "Centrocampista", "2000s"],
    ["Abedi Pele", "Ghana", "Marseille", "Mediapunta", "1990s"],
    ["Tony Yeboah", "Ghana", "Eintracht Frankfurt", "Delantero centro", "1990s"],
    ["Samuel Kuffour", "Ghana", "Bayern Múnich", "Defensa central", "1990s-2000s"],
    ["Michael Essien", "Ghana", "Chelsea", "Centrocampista defensivo", "2000s"],
    ["Gervais Yao Kouassi", "Costa de Marfil", "Arsenal", "Extremo", "2010s"],
    ["Mahamadou Diarra", "Mali", "Real Madrid", "Centrocampista defensivo", "2000s"],
    ["Fredi Kanouté", "Mali", "Sevilla", "Delantero centro", "2000s"],
    ["El Hadji Diouf", "Senegal", "Liverpool", "Delantero", "2000s"],
    ["Henri Camara", "Senegal", "Wigan Athletic", "Delantero", "2000s"],
    ["Papa Bouba Diop", "Senegal", "Fulham", "Centrocampista defensivo", "2000s"],
    ["Aliou Cissé", "Senegal", "Birmingham City", "Centrocampista", "2000s"],
    ["Jari Litmanen", "Finlandia", "Ajax", "Mediapunta", "1990s-2000s"],
    ["Tomas Brolin", "Suecia", "Parma", "Mediapunta", "1990s"],
    ["Henrik Larsson", "Suecia", "Celtic", "Delantero", "2000s"],
    ["Frederik Ljungberg", "Suecia", "Arsenal", "Centrocampista", "2000s"],
    ["Sami Hyypiä", "Finlandia", "Liverpool", "Defensa central", "2000s"],
    ["Eidur Gudjohnsen", "Islandia", "Chelsea", "Delantero", "2000s"],
    ["John Arne Riise", "Noruega", "Liverpool", "Lateral izquierdo", "2000s"],
    ["Tore André Flo", "Noruega", "Chelsea", "Delantero", "1990s-2000s"],
    ["Gunnar Nordahl", "Suecia", "AC Milan", "Delantero", "1950s"],
    ["Nils Liedholm", "Suecia", "AC Milan", "Centrocampista", "1950s"],
    ["Kevin Keegan", "Inglaterra", "Liverpool", "Delantero", "1970s"],
    ["Gary Lineker", "Inglaterra", "Leicester City", "Delantero", "1980s-1990s"],
    ["Paul Gascoigne", "Inglaterra", "Tottenham Hotspur", "Centrocampista ofensivo", "1990s"],
    ["Bryan Robson", "Inglaterra", "Manchester United", "Centrocampista", "1980s"],
    ["Stuart Pearce", "Inglaterra", "Nottingham Forest", "Lateral izquierdo", "1990s"],
    ["Tony Adams", "Inglaterra", "Arsenal", "Defensa central", "1990s"],
    ["Ian Wright", "Inglaterra", "Arsenal", "Delantero", "1990s"],
    ["David Seaman", "Inglaterra", "Arsenal", "Portero", "1990s-2000s"],
    ["Peter Shilton", "Inglaterra", "Nottingham Forest", "Portero", "1970s-1980s"],
    ["Gordon Banks", "Inglaterra", "Leicester City", "Portero", "1960s-1970s"],
    ["Kenny Dalglish", "Escocia", "Liverpool", "Delantero", "1970s-1980s"],
    ["Denis Law", "Escocia", "Manchester United", "Delantero", "1960s"],
    ["Graeme Souness", "Escocia", "Liverpool", "Centrocampista", "1980s"],
    ["Alan Hansen", "Escocia", "Liverpool", "Defensa central", "1980s"],
    ["Neville Southall", "Gales", "Everton", "Portero", "1980s-1990s"],
    ["Ian Rush", "Gales", "Liverpool", "Delantero", "1980s"],
    ["Mark Hughes", "Gales", "Manchester United", "Delantero", "1990s"],
    ["Liam Brady", "Irlanda", "Arsenal", "Centrocampista", "1970s-1980s"],
    ["Paul McGrath", "Irlanda", "Aston Villa", "Defensa central", "1990s"],
    ["José Luis Chilavert", "Paraguay", "Vélez Sarsfield", "Portero", "1990s"],
    ["Carlos Valderrama", "Colombia", "Deportivo Cali", "Centrocampista", "1990s"],
    ["Faustino Asprilla", "Colombia", "Parma", "Delantero", "1990s"],
    ["Freddy Rincón", "Colombia", "Corinthians", "Centrocampista", "1990s"],
    ["René Higuita", "Colombia", "Atlético Nacional", "Portero", "1990s"],
    ["Iván Zamorano", "Chile", "Real Madrid", "Delantero", "1990s"],
    ["Marcelo Salas", "Chile", "Lazio", "Delantero", "1990s-2000s"],
    ["Elías Figueroa", "Chile", "Internacional", "Defensa central", "1970s"],
    ["Paolo Montero", "Uruguay", "Juventus", "Defensa central", "1990s-2000s"],
    ["Álvaro Recoba", "Uruguay", "Inter de Milán", "Mediapunta", "2000s"],
    ["Diego Forlán", "Uruguay", "Atlético de Madrid", "Delantero", "2000s-2010s"],
    ["Obafemi Martins", "Nigeria", "Inter de Milán", "Delantero", "2000s"],
    ["George Campos", "México", "Pumas UNAM", "Portero / Delantero", "1990s"],
    ["Cuauhtémoc Blanco", "México", "América", "Mediapunta", "1990s-2000s"],
    ["Rafael Márquez", "México", "Barcelona", "Defensa central", "2000s-2010s"],
    ["Jared Borgetti", "México", "Santos Laguna", "Delantero centro", "2000s"],
    ["Hidetoshi Nakata", "Japón", "Roma", "Centrocampista ofensivo", "1990s-2000s"],
    ["Shunsuke Nakamura", "Japón", "Celtic", "Mediapunta", "2000s"],
    ["Ali Daei", "Irán", "Bayern Múnich", "Delantero centro", "1990s"],
    ["Park Ji-sung", "Corea del Sur", "Manchester United", "Centrocampista", "2000s"],
    ["Tim Howard", "Estados Unidos", "Everton", "Portero", "2000s-2010s"],
    ["Clint Dempsey", "Estados Unidos", "Fulham", "Mediapunta", "2000s-2010s"],
    ["Landon Donovan", "Estados Unidos", "LA Galaxy", "Delantero", "2000s-2010s"],
    ["Cláudio Taffarel", "Brasil", "Galatasaray", "Portero", "1990s"],
    ["Dida Silva", "Brasil", "AC Milan", "Portero", "2000s"],
    ["Aldair Santos", "Brasil", "AS Roma", "Defensa central", "1990s"],
    ["Branco", "Brasil", "FC Porto", "Lateral izquierdo", "1980s-1990s"],
    ["Jorginho", "Brasil", "Bayern Múnich", "Lateral derecho", "1990s"],
    ["Dunga", "Brasil", "Fiorentina", "Centrocampista defensivo", "1990s"],
    ["Mauro Silva", "Brasil", "Deportivo La Coruña", "Centrocampista defensivo", "1990s"],
    ["Raí", "Brasil", "Paris Saint-Germain", "Centrocampista ofensivo", "1990s"],
    ["Leonardo Araújo", "Brasil", "AC Milan", "Centrocampista", "1990s"],
    ["Denilson de Oliveira", "Brasil", "Real Betis", "Extremo", "1990s-2000s"],
    ["Juninho Pernambucano", "Brasil", "Olympique de Lyon", "Centrocampista", "2000s"],
    ["Careca", "Brasil", "Napoli", "Delantero", "1980s-1990s"],
    ["Tostão", "Brasil", "Cruzeiro", "Mediapunta", "1960s-1970s"],
    ["Jairzinho", "Brasil", "Botafogo", "Extremo derecho", "1960s-1970s"],
    ["Gérson", "Brasil", "Botafogo", "Centrocampista", "1960s-1970s"],
    ["Rivellino", "Brasil", "Corinthians", "Mediapunta", "1970s"],
    ["Carlos Alberto", "Brasil", "Santos", "Lateral derecho", "1960s-1970s"],
    ["Nílton Santos", "Brasil", "Botafogo", "Lateral izquierdo", "1950s-1960s"],
    ["Djalma Santos", "Brasil", "Palmeiras", "Lateral derecho", "1950s-1960s"],
    ["Zito", "Brasil", "Santos", "Centrocampista defensivo", "1950s-1960s"],
    ["Vavá", "Brasil", "Vasco da Gama", "Delantero", "1950s-1960s"],
    ["Mário Zagallo", "Brasil", "Botafogo", "Extremo izquierdo", "1950s-1960s"]
];

function buildCurrentPlayers(arr) {
    let result = [];
    arr.forEach(p => {
        result.push({
            name: p[0],
            nationality: p[1],
            club: p[2],
            previous_club: p[3],
            position: p[4],
            league: p[5],
        });
    });
    return result;
}

function buildLegendPlayers(arr) {
    let result = [];
    arr.forEach(p => {
        result.push({
            name: p[0],
            nationality: p[1],
            famous_club: p[2],
            position: p[3],
            era: p[4],
        });
    });
    return result;
}

fs.writeFileSync('data/players_current.json', JSON.stringify(buildCurrentPlayers(currentPlayersRaw), null, 2));
fs.writeFileSync('data/players_legends.json', JSON.stringify(buildLegendPlayers(legendPlayersRaw), null, 2));
console.log('Successfully generated clean, accurate arrays of strictly 200 unnumbered players.');
